### ISSUE TITLE
ProviderSpanFilter里的ApplicationContextAwareBean.CONTEXT为null 

### ISSUE THREAD

**Issue by qiyue49** [jessyZu/dubbo-zipkin-spring-starter#2]
dubbo 和boot的工程是分开的，请问是不是dubbo端需要做定制化开发？

**Comment by jessyZu** [comment]
请确保dubbo服务的Bean和dubbo-zipkin-spring-starter 里的Bean在一个容器里启动，这样dubbo-zipkin-spring-starter 在初始化的时候，可以进行正确的装配。

**Comment by qiyue49** [comment]
ProviderSpanFilter
tracer = ApplicationContextAwareBean.CONTEXT.getBean(Tracer.class); CONTEXT不会空了， 但是Trace.class这个类容器没有办法找到这个bean
在spring容器启动里面加入<bean id="dubboAware" class="com.github.jessyZu.dz.ApplicationContextAwareBean" />  类似方式  会报其他bean找不到？请问有啥方法可以一次性把dubbo-zipkin-spring-starter 里的Bean在容器启动？

**Comment by jessyZu** [comment]
@qiyue49 你可以显示地去配置Tracer 这个Bean，就像正常的spring bean配置一样，dubbo-zipkin-spring-starter 只是帮你配置了而已。

**Comment by shenzhuan** [comment]
如果没有用springboot的话  dubbo怎么整合呢

**Comment by jessyZu** [comment]
@shenzhuan 在使用dubbo的工程里，加入dubbo-zipkin-spring-starter依赖,然后自己配置bean的初始化
```
  @Bean
    public SpanInjector<RpcContext> dubboSpanInjector() {
        return new DubboSpanInjector();
    }


    @Bean
    public SpanExtractor<RpcContext> dubboSpanExtractor(Random random) {
        return new DubboSpanExtractor(random);
    }
```
