### ISSUE TITLE
span name最大长度50

### ISSUE THREAD

**Issue by danny-zhu** [jessyZu/dubbo-zipkin-spring-starter#4]
为什么最后拿到的span name限制为50个字符，不够用的

**Comment by danny-zhu** [comment]
sleuth搞的鬼
`If your span contains a name greater than 50 chars, then that name will be truncated to 50 chars. Your names have to be explicit and concrete. Big names lead to latency issues and sometimes even thrown exceptions.`

**Comment by jessyZu** [comment]
这个sleuth逻辑，作为集成者，不应该去改变任何逻辑
