### ISSUE TITLE
数据追踪不正确

### ISSUE THREAD

**Issue by wc394915432** [jessyZu/dubbo-zipkin-spring-starter#8]
我使用dubbo consumer调用了N次provider 才仅仅有一条数据记录，而只调用一次的时候根本不会有记录，请问这是怎么回事？我使用的是SPRING BOOT + DUBBO +ZOOKEEPER

**Comment by wonderlq** [comment]
是不是采集率的配置太低了？

**Comment by wonderlq** [comment]
是不是采集率的配置太低了？

**Comment by wc394915432** [comment]
正是采集率问题。

**Comment by wangchenyan** [comment]
请问怎么配置采样率？
