### ISSUE TITLE
配置项好少，就一个开关？zipkin地址配置呢？

### ISSUE THREAD

**Issue by ExtremeYu** [jessyZu/dubbo-zipkin-spring-starter#9]

**Comment by reymont** [comment]
@ExtremeYu 改下项目的application.properties文件就可以了
src/test/java/resources/application.properties
```conf
spring.sleuth.sampler.percentage=1
spring.application.name=dubbo-zipkin-test
spring.zipkin.baseUrl=http://zipkin-host:9411
```

**Comment by jessyZu** [comment]
参考spring cloud的sleuth 配置，这个项目是集成了sleuth 
https://spring.io/projects/spring-cloud-sleuth
